ALTER TABLE subscription_plans 
ADD COLUMN IF NOT EXISTS amc_amount NUMERIC(12,2) DEFAULT 0 NOT NULL,
ADD COLUMN IF NOT EXISTS ai_credits INTEGER DEFAULT 0 NOT NULL,
ADD COLUMN IF NOT EXISTS storage_limit_gb INTEGER DEFAULT 1 NOT NULL,
ADD COLUMN IF NOT EXISTS is_default BOOLEAN DEFAULT FALSE NOT NULL,
ADD COLUMN IF NOT EXISTS badge_color VARCHAR(50) DEFAULT 'secondary' NOT NULL;
