-- ═══════════════════════════════════════════════════════════════════════════
--  Seed the GLOBAL document field dictionary — the PII classification policy.
--
--  820 rows across all 83 categories. is_pii = true means the value is
--  SEALED under the vault key and never reaches an AI; false means it lands in
--  the open tier where search, expiry reminders and the AI can read it.
--
--  Every category gets at least the baseline set, because an unclassified field
--  FAILS OPEN — with no row saying otherwise it is treated as non-PII.
--
--  Mirrors DOCUMENT_CATEGORY_FIELD_SEED in src/lib/documentCategoryFields.ts;
--  tests/documentCategoryFields.test.ts diffs this block against that constant.
--  Regenerate rather than hand-edit — see that file's header.
--
--  Joined on `code` because category ids are generated at apply time.
--  Runs after 0006, so document_categories no longer has a tenant_id to filter.
--  Forward-only and re-runnable: ON CONFLICT DO NOTHING against the partial
--  unique index over (category_id, field_key) WHERE tenant_id IS NULL, so
--  tenant overrides are never touched.
-- ═══════════════════════════════════════════════════════════════════════════

INSERT INTO "document_category_fields"
  ("category_id","field_key","field_label","data_type","is_pii","is_required","sort_order")
SELECT dc.id, v.field_key, v.field_label, v.data_type, v.is_pii, v.is_required, v.sort_order
FROM (VALUES
  ('identity.aadhaar_card','document_title','Document Title','text',false,false,10),
  ('identity.aadhaar_card','aadhaar_number','Aadhaar Number','text',true,true,20),
  ('identity.aadhaar_card','date_of_birth','Date of Birth','date',true,false,30),
  ('identity.aadhaar_card','gender','Gender','text',false,false,40),
  ('identity.aadhaar_card','address','Address','longtext',true,false,50),
  ('identity.aadhaar_card','holder_name','Holder Name','text',true,false,60),
  ('identity.aadhaar_card','issue_date','Issue Date','date',false,false,70),
  ('identity.aadhaar_card','notes','Notes','longtext',true,false,80),
  ('identity.pan_card','document_title','Document Title','text',false,false,10),
  ('identity.pan_card','pan_number','PAN Number','text',true,true,20),
  ('identity.pan_card','father_name','Father''s Name','text',true,false,30),
  ('identity.pan_card','date_of_birth','Date of Birth','date',true,false,40),
  ('identity.pan_card','holder_name','Holder Name','text',true,false,50),
  ('identity.pan_card','issue_date','Issue Date','date',false,false,60),
  ('identity.pan_card','notes','Notes','longtext',true,false,70),
  ('identity.passport','document_title','Document Title','text',false,false,10),
  ('identity.passport','passport_number','Passport Number','text',true,true,20),
  ('identity.passport','date_of_birth','Date of Birth','date',true,false,30),
  ('identity.passport','place_of_birth','Place of Birth','text',false,false,40),
  ('identity.passport','place_of_issue','Place of Issue','text',false,false,50),
  ('identity.passport','issuing_authority','Issuing Authority','text',false,false,60),
  ('identity.passport','expiry_date','Expiry Date','date',false,false,70),
  ('identity.passport','holder_name','Holder Name','text',true,false,80),
  ('identity.passport','issue_date','Issue Date','date',false,false,90),
  ('identity.passport','notes','Notes','longtext',true,false,100),
  ('identity.voter_id','document_title','Document Title','text',false,false,10),
  ('identity.voter_id','voter_id_number','Voter ID Number','text',true,true,20),
  ('identity.voter_id','constituency','Constituency','text',false,false,30),
  ('identity.voter_id','address','Address','longtext',true,false,40),
  ('identity.voter_id','holder_name','Holder Name','text',true,false,50),
  ('identity.voter_id','issue_date','Issue Date','date',false,false,60),
  ('identity.voter_id','notes','Notes','longtext',true,false,70),
  ('identity.driving_license','document_title','Document Title','text',false,false,10),
  ('identity.driving_license','license_number','License Number','text',true,true,20),
  ('identity.driving_license','vehicle_classes','Vehicle Classes','text',false,false,30),
  ('identity.driving_license','blood_group','Blood Group','text',true,false,40),
  ('identity.driving_license','issuing_authority','Issuing Authority','text',false,false,50),
  ('identity.driving_license','valid_from','Valid From','date',false,false,60),
  ('identity.driving_license','expiry_date','Expiry Date','date',false,false,70),
  ('identity.driving_license','holder_name','Holder Name','text',true,false,80),
  ('identity.driving_license','issue_date','Issue Date','date',false,false,90),
  ('identity.driving_license','notes','Notes','longtext',true,false,100),
  ('identity.birth_certificate','document_title','Document Title','text',false,false,10),
  ('identity.birth_certificate','registration_number','Registration Number','text',true,true,20),
  ('identity.birth_certificate','date_of_birth','Date of Birth','date',true,false,30),
  ('identity.birth_certificate','place_of_birth','Place of Birth','text',false,false,40),
  ('identity.birth_certificate','father_name','Father''s Name','text',true,false,50),
  ('identity.birth_certificate','mother_name','Mother''s Name','text',true,false,60),
  ('identity.birth_certificate','issuing_authority','Issuing Authority','text',false,false,70),
  ('identity.birth_certificate','holder_name','Holder Name','text',true,false,80),
  ('identity.birth_certificate','issue_date','Issue Date','date',false,false,90),
  ('identity.birth_certificate','notes','Notes','longtext',true,false,100),
  ('identity.death_certificate','document_title','Document Title','text',false,false,10),
  ('identity.death_certificate','registration_number','Registration Number','text',true,true,20),
  ('identity.death_certificate','date_of_death','Date of Death','date',true,false,30),
  ('identity.death_certificate','place_of_death','Place of Death','text',false,false,40),
  ('identity.death_certificate','issuing_authority','Issuing Authority','text',false,false,50),
  ('identity.death_certificate','holder_name','Holder Name','text',true,false,60),
  ('identity.death_certificate','issue_date','Issue Date','date',false,false,70),
  ('identity.death_certificate','notes','Notes','longtext',true,false,80),
  ('identity.ration_card','document_title','Document Title','text',false,false,10),
  ('identity.ration_card','ration_card_number','Ration Card Number','text',true,true,20),
  ('identity.ration_card','card_category','Card Category','text',false,false,30),
  ('identity.ration_card','member_names','Member Names','longtext',true,false,40),
  ('identity.ration_card','address','Address','longtext',true,false,50),
  ('identity.ration_card','holder_name','Holder Name','text',true,false,60),
  ('identity.ration_card','issue_date','Issue Date','date',false,false,70),
  ('identity.ration_card','notes','Notes','longtext',true,false,80),
  ('bank_investments.bank_statements_passbooks','document_title','Document Title','text',false,false,10),
  ('bank_investments.bank_statements_passbooks','account_number','Account Number','text',true,true,20),
  ('bank_investments.bank_statements_passbooks','ifsc_code','IFSC Code','text',true,false,30),
  ('bank_investments.bank_statements_passbooks','bank_name','Bank Name','text',false,false,40),
  ('bank_investments.bank_statements_passbooks','branch_name','Branch Name','text',false,false,50),
  ('bank_investments.bank_statements_passbooks','account_type','Account Type','text',false,false,60),
  ('bank_investments.bank_statements_passbooks','statement_period','Statement Period','text',false,false,70),
  ('bank_investments.bank_statements_passbooks','closing_balance','Closing Balance','currency',true,false,80),
  ('bank_investments.bank_statements_passbooks','holder_name','Holder Name','text',true,false,90),
  ('bank_investments.bank_statements_passbooks','issue_date','Issue Date','date',false,false,100),
  ('bank_investments.bank_statements_passbooks','notes','Notes','longtext',true,false,110),
  ('bank_investments.fixed_deposit_receipts','document_title','Document Title','text',false,false,10),
  ('bank_investments.fixed_deposit_receipts','fd_receipt_number','FD Receipt Number','text',true,true,20),
  ('bank_investments.fixed_deposit_receipts','bank_name','Bank Name','text',false,false,30),
  ('bank_investments.fixed_deposit_receipts','principal_amount','Principal Amount','currency',true,false,40),
  ('bank_investments.fixed_deposit_receipts','interest_rate','Interest Rate (%)','number',false,false,50),
  ('bank_investments.fixed_deposit_receipts','maturity_amount','Maturity Amount','currency',true,false,60),
  ('bank_investments.fixed_deposit_receipts','maturity_date','Maturity Date','date',false,false,70),
  ('bank_investments.fixed_deposit_receipts','nominee_name','Nominee Name','text',true,false,80),
  ('bank_investments.fixed_deposit_receipts','holder_name','Holder Name','text',true,false,90),
  ('bank_investments.fixed_deposit_receipts','issue_date','Issue Date','date',false,false,100),
  ('bank_investments.fixed_deposit_receipts','notes','Notes','longtext',true,false,110),
  ('bank_investments.mutual_fund_statements','document_title','Document Title','text',false,false,10),
  ('bank_investments.mutual_fund_statements','folio_number','Folio Number','text',true,true,20),
  ('bank_investments.mutual_fund_statements','fund_house','Fund House','text',false,false,30),
  ('bank_investments.mutual_fund_statements','scheme_name','Scheme Name','text',false,false,40),
  ('bank_investments.mutual_fund_statements','units_held','Units Held','number',true,false,50),
  ('bank_investments.mutual_fund_statements','current_value','Current Value','currency',true,false,60),
  ('bank_investments.mutual_fund_statements','statement_period','Statement Period','text',false,false,70),
  ('bank_investments.mutual_fund_statements','holder_name','Holder Name','text',true,false,80),
  ('bank_investments.mutual_fund_statements','issue_date','Issue Date','date',false,false,90),
  ('bank_investments.mutual_fund_statements','notes','Notes','longtext',true,false,100),
  ('bank_investments.demat_trading_documents','document_title','Document Title','text',false,false,10),
  ('bank_investments.demat_trading_documents','demat_account_number','Demat Account Number','text',true,true,20),
  ('bank_investments.demat_trading_documents','depository','Depository','text',false,false,30),
  ('bank_investments.demat_trading_documents','depository_participant','Depository Participant','text',false,false,40),
  ('bank_investments.demat_trading_documents','broker_name','Broker Name','text',false,false,50),
  ('bank_investments.demat_trading_documents','holdings_value','Holdings Value','currency',true,false,60),
  ('bank_investments.demat_trading_documents','holder_name','Holder Name','text',true,false,70),
  ('bank_investments.demat_trading_documents','issue_date','Issue Date','date',false,false,80),
  ('bank_investments.demat_trading_documents','notes','Notes','longtext',true,false,90),
  ('bank_investments.loan_agreements','document_title','Document Title','text',false,false,10),
  ('bank_investments.loan_agreements','loan_account_number','Loan Account Number','text',true,true,20),
  ('bank_investments.loan_agreements','lender_name','Lender Name','text',false,false,30),
  ('bank_investments.loan_agreements','loan_type','Loan Type','text',false,false,40),
  ('bank_investments.loan_agreements','loan_amount','Loan Amount','currency',true,false,50),
  ('bank_investments.loan_agreements','interest_rate','Interest Rate (%)','number',false,false,60),
  ('bank_investments.loan_agreements','tenure_months','Tenure (Months)','number',false,false,70),
  ('bank_investments.loan_agreements','emi_amount','EMI Amount','currency',true,false,80),
  ('bank_investments.loan_agreements','disbursal_date','Disbursal Date','date',false,false,90),
  ('bank_investments.loan_agreements','holder_name','Holder Name','text',true,false,100),
  ('bank_investments.loan_agreements','issue_date','Issue Date','date',false,false,110),
  ('bank_investments.loan_agreements','notes','Notes','longtext',true,false,120),
  ('bank_investments.credit_card_statements','document_title','Document Title','text',false,false,10),
  ('bank_investments.credit_card_statements','card_last_four','Card Last 4 Digits','text',true,true,20),
  ('bank_investments.credit_card_statements','issuer_name','Issuer Name','text',false,false,30),
  ('bank_investments.credit_card_statements','statement_period','Statement Period','text',false,false,40),
  ('bank_investments.credit_card_statements','total_due','Total Amount Due','currency',true,false,50),
  ('bank_investments.credit_card_statements','credit_limit','Credit Limit','currency',true,false,60),
  ('bank_investments.credit_card_statements','due_date','Payment Due Date','date',false,false,70),
  ('bank_investments.credit_card_statements','holder_name','Holder Name','text',true,false,80),
  ('bank_investments.credit_card_statements','issue_date','Issue Date','date',false,false,90),
  ('bank_investments.credit_card_statements','notes','Notes','longtext',true,false,100),
  ('bank_investments.itr_form16','document_title','Document Title','text',false,false,10),
  ('bank_investments.itr_form16','acknowledgement_number','Acknowledgement Number','text',true,true,20),
  ('bank_investments.itr_form16','pan_number','PAN Number','text',true,false,30),
  ('bank_investments.itr_form16','assessment_year','Assessment Year','text',false,false,40),
  ('bank_investments.itr_form16','employer_name','Employer Name','text',false,false,50),
  ('bank_investments.itr_form16','gross_income','Gross Income','currency',true,false,60),
  ('bank_investments.itr_form16','tax_paid','Tax Paid','currency',true,false,70),
  ('bank_investments.itr_form16','holder_name','Holder Name','text',true,false,80),
  ('bank_investments.itr_form16','issue_date','Issue Date','date',false,false,90),
  ('bank_investments.itr_form16','notes','Notes','longtext',true,false,100),
  ('bank_investments.epf_ppf_nps_statements','document_title','Document Title','text',false,false,10),
  ('bank_investments.epf_ppf_nps_statements','uan_number','UAN Number','text',true,true,20),
  ('bank_investments.epf_ppf_nps_statements','account_number','Account Number','text',true,false,30),
  ('bank_investments.epf_ppf_nps_statements','scheme_type','Scheme Type','text',false,false,40),
  ('bank_investments.epf_ppf_nps_statements','employer_name','Employer Name','text',false,false,50),
  ('bank_investments.epf_ppf_nps_statements','closing_balance','Closing Balance','currency',true,false,60),
  ('bank_investments.epf_ppf_nps_statements','statement_period','Statement Period','text',false,false,70),
  ('bank_investments.epf_ppf_nps_statements','holder_name','Holder Name','text',true,false,80),
  ('bank_investments.epf_ppf_nps_statements','issue_date','Issue Date','date',false,false,90),
  ('bank_investments.epf_ppf_nps_statements','notes','Notes','longtext',true,false,100),
  ('bank_investments.cheque_books','document_title','Document Title','text',false,false,10),
  ('bank_investments.cheque_books','account_number','Account Number','text',true,true,20),
  ('bank_investments.cheque_books','cheque_series','Cheque Series','text',true,false,30),
  ('bank_investments.cheque_books','bank_name','Bank Name','text',false,false,40),
  ('bank_investments.cheque_books','branch_name','Branch Name','text',false,false,50),
  ('bank_investments.cheque_books','holder_name','Holder Name','text',true,false,60),
  ('bank_investments.cheque_books','issue_date','Issue Date','date',false,false,70),
  ('bank_investments.cheque_books','notes','Notes','longtext',true,false,80),
  ('bank_investments.bank_locker_agreement','document_title','Document Title','text',false,false,10),
  ('bank_investments.bank_locker_agreement','locker_number','Locker Number','text',true,true,20),
  ('bank_investments.bank_locker_agreement','bank_name','Bank Name','text',false,false,30),
  ('bank_investments.bank_locker_agreement','branch_name','Branch Name','text',false,false,40),
  ('bank_investments.bank_locker_agreement','annual_rent','Annual Rent','currency',true,false,50),
  ('bank_investments.bank_locker_agreement','agreement_date','Agreement Date','date',false,false,60),
  ('bank_investments.bank_locker_agreement','inventory_list','Inventory List','longtext',true,false,70),
  ('bank_investments.bank_locker_agreement','holder_name','Holder Name','text',true,false,80),
  ('bank_investments.bank_locker_agreement','issue_date','Issue Date','date',false,false,90),
  ('bank_investments.bank_locker_agreement','notes','Notes','longtext',true,false,100),
  ('insurance.life_policies','document_title','Document Title','text',false,false,10),
  ('insurance.life_policies','policy_number','Policy Number','text',true,true,20),
  ('insurance.life_policies','insurer_name','Insurer Name','text',false,false,30),
  ('insurance.life_policies','plan_name','Plan Name','text',false,false,40),
  ('insurance.life_policies','sum_assured','Sum Assured','currency',true,false,50),
  ('insurance.life_policies','premium_amount','Premium Amount','currency',true,false,60),
  ('insurance.life_policies','premium_frequency','Premium Frequency','text',false,false,70),
  ('insurance.life_policies','nominee_name','Nominee Name','text',true,false,80),
  ('insurance.life_policies','policy_term_years','Policy Term (Years)','number',false,false,90),
  ('insurance.life_policies','maturity_date','Maturity Date','date',false,false,100),
  ('insurance.life_policies','renewal_due_date','Renewal Due Date','date',false,false,110),
  ('insurance.life_policies','holder_name','Holder Name','text',true,false,120),
  ('insurance.life_policies','issue_date','Issue Date','date',false,false,130),
  ('insurance.life_policies','notes','Notes','longtext',true,false,140),
  ('insurance.health_policies','document_title','Document Title','text',false,false,10),
  ('insurance.health_policies','policy_number','Policy Number','text',true,true,20),
  ('insurance.health_policies','insurer_name','Insurer Name','text',false,false,30),
  ('insurance.health_policies','plan_name','Plan Name','text',false,false,40),
  ('insurance.health_policies','coverage_type','Coverage Type','text',false,false,50),
  ('insurance.health_policies','sum_insured','Sum Insured','currency',true,false,60),
  ('insurance.health_policies','premium_amount','Premium Amount','currency',true,false,70),
  ('insurance.health_policies','member_names','Covered Members','longtext',true,false,80),
  ('insurance.health_policies','renewal_due_date','Renewal Due Date','date',false,false,90),
  ('insurance.health_policies','holder_name','Holder Name','text',true,false,100),
  ('insurance.health_policies','issue_date','Issue Date','date',false,false,110),
  ('insurance.health_policies','notes','Notes','longtext',true,false,120),
  ('insurance.vehicle_policies','document_title','Document Title','text',false,false,10),
  ('insurance.vehicle_policies','policy_number','Policy Number','text',true,true,20),
  ('insurance.vehicle_policies','insurer_name','Insurer Name','text',false,false,30),
  ('insurance.vehicle_policies','registration_number','Vehicle Registration Number','text',true,false,40),
  ('insurance.vehicle_policies','coverage_type','Coverage Type','text',false,false,50),
  ('insurance.vehicle_policies','idv_amount','Insured Declared Value','currency',true,false,60),
  ('insurance.vehicle_policies','premium_amount','Premium Amount','currency',true,false,70),
  ('insurance.vehicle_policies','valid_from','Valid From','date',false,false,80),
  ('insurance.vehicle_policies','valid_to','Valid To','date',false,false,90),
  ('insurance.vehicle_policies','holder_name','Holder Name','text',true,false,100),
  ('insurance.vehicle_policies','issue_date','Issue Date','date',false,false,110),
  ('insurance.vehicle_policies','notes','Notes','longtext',true,false,120),
  ('insurance.home_property_policies','document_title','Document Title','text',false,false,10),
  ('insurance.home_property_policies','policy_number','Policy Number','text',true,true,20),
  ('insurance.home_property_policies','insurer_name','Insurer Name','text',false,false,30),
  ('insurance.home_property_policies','property_address','Property Address','longtext',true,false,40),
  ('insurance.home_property_policies','coverage_type','Coverage Type','text',false,false,50),
  ('insurance.home_property_policies','sum_insured','Sum Insured','currency',true,false,60),
  ('insurance.home_property_policies','premium_amount','Premium Amount','currency',true,false,70),
  ('insurance.home_property_policies','renewal_due_date','Renewal Due Date','date',false,false,80),
  ('insurance.home_property_policies','holder_name','Holder Name','text',true,false,90),
  ('insurance.home_property_policies','issue_date','Issue Date','date',false,false,100),
  ('insurance.home_property_policies','notes','Notes','longtext',true,false,110),
  ('insurance.term_policies','document_title','Document Title','text',false,false,10),
  ('insurance.term_policies','policy_number','Policy Number','text',true,true,20),
  ('insurance.term_policies','insurer_name','Insurer Name','text',false,false,30),
  ('insurance.term_policies','sum_assured','Sum Assured','currency',true,false,40),
  ('insurance.term_policies','premium_amount','Premium Amount','currency',true,false,50),
  ('insurance.term_policies','policy_term_years','Policy Term (Years)','number',false,false,60),
  ('insurance.term_policies','nominee_name','Nominee Name','text',true,false,70),
  ('insurance.term_policies','renewal_due_date','Renewal Due Date','date',false,false,80),
  ('insurance.term_policies','holder_name','Holder Name','text',true,false,90),
  ('insurance.term_policies','issue_date','Issue Date','date',false,false,100),
  ('insurance.term_policies','notes','Notes','longtext',true,false,110),
  ('insurance.premium_receipts','document_title','Document Title','text',false,false,10),
  ('insurance.premium_receipts','receipt_number','Receipt Number','text',true,true,20),
  ('insurance.premium_receipts','policy_number','Policy Number','text',true,false,30),
  ('insurance.premium_receipts','insurer_name','Insurer Name','text',false,false,40),
  ('insurance.premium_receipts','amount_paid','Amount Paid','currency',true,false,50),
  ('insurance.premium_receipts','payment_mode','Payment Mode','text',false,false,60),
  ('insurance.premium_receipts','payment_date','Payment Date','date',false,false,70),
  ('insurance.premium_receipts','holder_name','Holder Name','text',true,false,80),
  ('insurance.premium_receipts','issue_date','Issue Date','date',false,false,90),
  ('insurance.premium_receipts','notes','Notes','longtext',true,false,100),
  ('property_legal.sale_deed_title','document_title','Document Title','text',false,false,10),
  ('property_legal.sale_deed_title','deed_registration_number','Deed Registration Number','text',true,true,20),
  ('property_legal.sale_deed_title','property_address','Property Address','longtext',true,false,30),
  ('property_legal.sale_deed_title','survey_number','Survey Number','text',true,false,40),
  ('property_legal.sale_deed_title','seller_name','Seller Name','text',true,false,50),
  ('property_legal.sale_deed_title','buyer_name','Buyer Name','text',true,false,60),
  ('property_legal.sale_deed_title','consideration_amount','Consideration Amount','currency',true,false,70),
  ('property_legal.sale_deed_title','built_up_area','Built-up Area','text',false,false,80),
  ('property_legal.sale_deed_title','sub_registrar_office','Sub-Registrar Office','text',false,false,90),
  ('property_legal.sale_deed_title','registration_date','Registration Date','date',false,false,100),
  ('property_legal.sale_deed_title','holder_name','Holder Name','text',true,false,110),
  ('property_legal.sale_deed_title','issue_date','Issue Date','date',false,false,120),
  ('property_legal.sale_deed_title','notes','Notes','longtext',true,false,130),
  ('property_legal.registration_stamp_duty_receipts','document_title','Document Title','text',false,false,10),
  ('property_legal.registration_stamp_duty_receipts','receipt_number','Receipt Number','text',true,true,20),
  ('property_legal.registration_stamp_duty_receipts','stamp_duty_amount','Stamp Duty Amount','currency',true,false,30),
  ('property_legal.registration_stamp_duty_receipts','registration_fee','Registration Fee','currency',true,false,40),
  ('property_legal.registration_stamp_duty_receipts','sub_registrar_office','Sub-Registrar Office','text',false,false,50),
  ('property_legal.registration_stamp_duty_receipts','payment_date','Payment Date','date',false,false,60),
  ('property_legal.registration_stamp_duty_receipts','holder_name','Holder Name','text',true,false,70),
  ('property_legal.registration_stamp_duty_receipts','issue_date','Issue Date','date',false,false,80),
  ('property_legal.registration_stamp_duty_receipts','notes','Notes','longtext',true,false,90),
  ('property_legal.encumbrance_certificate','document_title','Document Title','text',false,false,10),
  ('property_legal.encumbrance_certificate','certificate_number','Certificate Number','text',true,true,20),
  ('property_legal.encumbrance_certificate','property_address','Property Address','longtext',true,false,30),
  ('property_legal.encumbrance_certificate','survey_number','Survey Number','text',true,false,40),
  ('property_legal.encumbrance_certificate','period_covered','Period Covered','text',false,false,50),
  ('property_legal.encumbrance_certificate','issuing_authority','Issuing Authority','text',false,false,60),
  ('property_legal.encumbrance_certificate','holder_name','Holder Name','text',true,false,70),
  ('property_legal.encumbrance_certificate','issue_date','Issue Date','date',false,false,80),
  ('property_legal.encumbrance_certificate','notes','Notes','longtext',true,false,90),
  ('property_legal.property_tax_receipts','document_title','Document Title','text',false,false,10),
  ('property_legal.property_tax_receipts','property_id','Property ID','text',true,true,20),
  ('property_legal.property_tax_receipts','receipt_number','Receipt Number','text',true,false,30),
  ('property_legal.property_tax_receipts','municipal_body','Municipal Body','text',false,false,40),
  ('property_legal.property_tax_receipts','assessment_year','Assessment Year','text',false,false,50),
  ('property_legal.property_tax_receipts','amount_paid','Amount Paid','currency',true,false,60),
  ('property_legal.property_tax_receipts','payment_date','Payment Date','date',false,false,70),
  ('property_legal.property_tax_receipts','holder_name','Holder Name','text',true,false,80),
  ('property_legal.property_tax_receipts','issue_date','Issue Date','date',false,false,90),
  ('property_legal.property_tax_receipts','notes','Notes','longtext',true,false,100),
  ('property_legal.will_nomination','document_title','Document Title','text',false,false,10),
  ('property_legal.will_nomination','registration_number','Registration Number','text',true,false,20),
  ('property_legal.will_nomination','testator_name','Testator Name','text',true,false,30),
  ('property_legal.will_nomination','beneficiary_names','Beneficiary Names','longtext',true,false,40),
  ('property_legal.will_nomination','executor_name','Executor Name','text',true,false,50),
  ('property_legal.will_nomination','witness_names','Witness Names','longtext',true,false,60),
  ('property_legal.will_nomination','execution_date','Execution Date','date',false,false,70),
  ('property_legal.will_nomination','holder_name','Holder Name','text',true,false,80),
  ('property_legal.will_nomination','issue_date','Issue Date','date',false,false,90),
  ('property_legal.will_nomination','notes','Notes','longtext',true,false,100),
  ('property_legal.power_of_attorney','document_title','Document Title','text',false,false,10),
  ('property_legal.power_of_attorney','registration_number','Registration Number','text',true,false,20),
  ('property_legal.power_of_attorney','principal_name','Principal Name','text',true,false,30),
  ('property_legal.power_of_attorney','attorney_name','Attorney Name','text',true,false,40),
  ('property_legal.power_of_attorney','powers_granted','Powers Granted','longtext',true,false,50),
  ('property_legal.power_of_attorney','execution_date','Execution Date','date',false,false,60),
  ('property_legal.power_of_attorney','valid_to','Valid To','date',false,false,70),
  ('property_legal.power_of_attorney','holder_name','Holder Name','text',true,false,80),
  ('property_legal.power_of_attorney','issue_date','Issue Date','date',false,false,90),
  ('property_legal.power_of_attorney','notes','Notes','longtext',true,false,100),
  ('property_legal.khata_mutation_certificates','document_title','Document Title','text',false,false,10),
  ('property_legal.khata_mutation_certificates','khata_number','Khata Number','text',true,true,20),
  ('property_legal.khata_mutation_certificates','property_address','Property Address','longtext',true,false,30),
  ('property_legal.khata_mutation_certificates','survey_number','Survey Number','text',true,false,40),
  ('property_legal.khata_mutation_certificates','owner_name','Owner Name','text',true,false,50),
  ('property_legal.khata_mutation_certificates','municipal_body','Municipal Body','text',false,false,60),
  ('property_legal.khata_mutation_certificates','mutation_date','Mutation Date','date',false,false,70),
  ('property_legal.khata_mutation_certificates','holder_name','Holder Name','text',true,false,80),
  ('property_legal.khata_mutation_certificates','issue_date','Issue Date','date',false,false,90),
  ('property_legal.khata_mutation_certificates','notes','Notes','longtext',true,false,100),
  ('property_legal.divorce_custody','document_title','Document Title','text',false,false,10),
  ('property_legal.divorce_custody','case_number','Case Number','text',true,true,20),
  ('property_legal.divorce_custody','party_names','Party Names','longtext',true,false,30),
  ('property_legal.divorce_custody','custody_terms','Custody Terms','longtext',true,false,40),
  ('property_legal.divorce_custody','court_name','Court Name','text',false,false,50),
  ('property_legal.divorce_custody','decree_date','Decree Date','date',false,false,60),
  ('property_legal.divorce_custody','holder_name','Holder Name','text',true,false,70),
  ('property_legal.divorce_custody','issue_date','Issue Date','date',false,false,80),
  ('property_legal.divorce_custody','notes','Notes','longtext',true,false,90),
  ('education.marksheets_certificates','document_title','Document Title','text',false,false,10),
  ('education.marksheets_certificates','roll_number','Roll Number','text',true,true,20),
  ('education.marksheets_certificates','student_name','Student Name','text',true,false,30),
  ('education.marksheets_certificates','board_university','Board / University','text',false,false,40),
  ('education.marksheets_certificates','institution_name','Institution Name','text',false,false,50),
  ('education.marksheets_certificates','exam_name','Examination','text',false,false,60),
  ('education.marksheets_certificates','passing_year','Year of Passing','text',false,false,70),
  ('education.marksheets_certificates','marks_obtained','Marks Obtained','text',true,false,80),
  ('education.marksheets_certificates','percentage','Percentage','number',true,false,90),
  ('education.marksheets_certificates','holder_name','Holder Name','text',true,false,100),
  ('education.marksheets_certificates','issue_date','Issue Date','date',false,false,110),
  ('education.marksheets_certificates','notes','Notes','longtext',true,false,120),
  ('education.degree_diploma','document_title','Document Title','text',false,false,10),
  ('education.degree_diploma','certificate_number','Certificate Number','text',true,true,20),
  ('education.degree_diploma','student_name','Student Name','text',true,false,30),
  ('education.degree_diploma','degree_name','Degree / Diploma','text',false,false,40),
  ('education.degree_diploma','specialization','Specialization','text',false,false,50),
  ('education.degree_diploma','board_university','Board / University','text',false,false,60),
  ('education.degree_diploma','passing_year','Year of Passing','text',false,false,70),
  ('education.degree_diploma','grade','Grade / Class','text',true,false,80),
  ('education.degree_diploma','holder_name','Holder Name','text',true,false,90),
  ('education.degree_diploma','issue_date','Issue Date','date',false,false,100),
  ('education.degree_diploma','notes','Notes','longtext',true,false,110),
  ('education.migration_transfer','document_title','Document Title','text',false,false,10),
  ('education.migration_transfer','certificate_number','Certificate Number','text',true,true,20),
  ('education.migration_transfer','student_name','Student Name','text',true,false,30),
  ('education.migration_transfer','institution_name','Institution Name','text',false,false,40),
  ('education.migration_transfer','board_university','Board / University','text',false,false,50),
  ('education.migration_transfer','holder_name','Holder Name','text',true,false,60),
  ('education.migration_transfer','issue_date','Issue Date','date',false,false,70),
  ('education.migration_transfer','notes','Notes','longtext',true,false,80),
  ('education.entrance_exam_scorecards','document_title','Document Title','text',false,false,10),
  ('education.entrance_exam_scorecards','roll_number','Roll Number','text',true,true,20),
  ('education.entrance_exam_scorecards','candidate_name','Candidate Name','text',true,false,30),
  ('education.entrance_exam_scorecards','exam_name','Examination','text',false,false,40),
  ('education.entrance_exam_scorecards','exam_year','Exam Year','text',false,false,50),
  ('education.entrance_exam_scorecards','score','Score','text',true,false,60),
  ('education.entrance_exam_scorecards','rank_obtained','Rank','text',true,false,70),
  ('education.entrance_exam_scorecards','holder_name','Holder Name','text',true,false,80),
  ('education.entrance_exam_scorecards','issue_date','Issue Date','date',false,false,90),
  ('education.entrance_exam_scorecards','notes','Notes','longtext',true,false,100),
  ('health_medical.records_prescriptions','document_title','Document Title','text',false,false,10),
  ('health_medical.records_prescriptions','patient_name','Patient Name','text',true,false,20),
  ('health_medical.records_prescriptions','diagnosis','Diagnosis','longtext',true,false,30),
  ('health_medical.records_prescriptions','prescription_text','Prescription','longtext',true,false,40),
  ('health_medical.records_prescriptions','doctor_name','Doctor Name','text',false,false,50),
  ('health_medical.records_prescriptions','hospital_name','Hospital / Clinic','text',false,false,60),
  ('health_medical.records_prescriptions','visit_date','Visit Date','date',false,false,70),
  ('health_medical.records_prescriptions','holder_name','Holder Name','text',true,false,80),
  ('health_medical.records_prescriptions','issue_date','Issue Date','date',false,false,90),
  ('health_medical.records_prescriptions','notes','Notes','longtext',true,false,100),
  ('health_medical.vaccination_certificates','document_title','Document Title','text',false,false,10),
  ('health_medical.vaccination_certificates','beneficiary_name','Beneficiary Name','text',true,false,20),
  ('health_medical.vaccination_certificates','beneficiary_id','Beneficiary ID','text',true,false,30),
  ('health_medical.vaccination_certificates','vaccine_name','Vaccine','text',false,false,40),
  ('health_medical.vaccination_certificates','dose_number','Dose Number','number',false,false,50),
  ('health_medical.vaccination_certificates','vaccination_centre','Vaccination Centre','text',false,false,60),
  ('health_medical.vaccination_certificates','vaccination_date','Vaccination Date','date',false,false,70),
  ('health_medical.vaccination_certificates','holder_name','Holder Name','text',true,false,80),
  ('health_medical.vaccination_certificates','issue_date','Issue Date','date',false,false,90),
  ('health_medical.vaccination_certificates','notes','Notes','longtext',true,false,100),
  ('health_medical.checkup_reports','document_title','Document Title','text',false,false,10),
  ('health_medical.checkup_reports','patient_name','Patient Name','text',true,false,20),
  ('health_medical.checkup_reports','test_results','Test Results','longtext',true,false,30),
  ('health_medical.checkup_reports','lab_name','Laboratory','text',false,false,40),
  ('health_medical.checkup_reports','referring_doctor','Referring Doctor','text',false,false,50),
  ('health_medical.checkup_reports','report_date','Report Date','date',false,false,60),
  ('health_medical.checkup_reports','holder_name','Holder Name','text',true,false,70),
  ('health_medical.checkup_reports','issue_date','Issue Date','date',false,false,80),
  ('health_medical.checkup_reports','notes','Notes','longtext',true,false,90),
  ('health_medical.discharge_summaries','document_title','Document Title','text',false,false,10),
  ('health_medical.discharge_summaries','patient_name','Patient Name','text',true,false,20),
  ('health_medical.discharge_summaries','diagnosis','Diagnosis','longtext',true,false,30),
  ('health_medical.discharge_summaries','treatment_summary','Treatment Summary','longtext',true,false,40),
  ('health_medical.discharge_summaries','hospital_name','Hospital','text',false,false,50),
  ('health_medical.discharge_summaries','admission_date','Admission Date','date',false,false,60),
  ('health_medical.discharge_summaries','discharge_date','Discharge Date','date',false,false,70),
  ('health_medical.discharge_summaries','holder_name','Holder Name','text',true,false,80),
  ('health_medical.discharge_summaries','issue_date','Issue Date','date',false,false,90),
  ('health_medical.discharge_summaries','notes','Notes','longtext',true,false,100),
  ('health_medical.insurance_claims','document_title','Document Title','text',false,false,10),
  ('health_medical.insurance_claims','claim_number','Claim Number','text',true,true,20),
  ('health_medical.insurance_claims','policy_number','Policy Number','text',true,false,30),
  ('health_medical.insurance_claims','patient_name','Patient Name','text',true,false,40),
  ('health_medical.insurance_claims','insurer_name','Insurer Name','text',false,false,50),
  ('health_medical.insurance_claims','claim_amount','Claim Amount','currency',true,false,60),
  ('health_medical.insurance_claims','approved_amount','Approved Amount','currency',true,false,70),
  ('health_medical.insurance_claims','claim_status','Claim Status','text',false,false,80),
  ('health_medical.insurance_claims','claim_date','Claim Date','date',false,false,90),
  ('health_medical.insurance_claims','holder_name','Holder Name','text',true,false,100),
  ('health_medical.insurance_claims','issue_date','Issue Date','date',false,false,110),
  ('health_medical.insurance_claims','notes','Notes','longtext',true,false,120),
  ('health_medical.disability_certificate','document_title','Document Title','text',false,false,10),
  ('health_medical.disability_certificate','certificate_number','Certificate Number','text',true,true,20),
  ('health_medical.disability_certificate','person_name','Person Name','text',true,false,30),
  ('health_medical.disability_certificate','disability_type','Disability Type','text',true,false,40),
  ('health_medical.disability_certificate','disability_percentage','Disability Percentage','number',true,false,50),
  ('health_medical.disability_certificate','issuing_authority','Issuing Authority','text',false,false,60),
  ('health_medical.disability_certificate','valid_to','Valid To','date',false,false,70),
  ('health_medical.disability_certificate','holder_name','Holder Name','text',true,false,80),
  ('health_medical.disability_certificate','issue_date','Issue Date','date',false,false,90),
  ('health_medical.disability_certificate','notes','Notes','longtext',true,false,100),
  ('employment.offer_appointment_letters','document_title','Document Title','text',false,false,10),
  ('employment.offer_appointment_letters','employee_name','Employee Name','text',true,false,20),
  ('employment.offer_appointment_letters','employer_name','Employer Name','text',false,false,30),
  ('employment.offer_appointment_letters','designation','Designation','text',false,false,40),
  ('employment.offer_appointment_letters','annual_ctc','Annual CTC','currency',true,false,50),
  ('employment.offer_appointment_letters','work_location','Work Location','text',false,false,60),
  ('employment.offer_appointment_letters','joining_date','Joining Date','date',false,false,70),
  ('employment.offer_appointment_letters','holder_name','Holder Name','text',true,false,80),
  ('employment.offer_appointment_letters','issue_date','Issue Date','date',false,false,90),
  ('employment.offer_appointment_letters','notes','Notes','longtext',true,false,100),
  ('employment.salary_slips','document_title','Document Title','text',false,false,10),
  ('employment.salary_slips','employee_id','Employee ID','text',true,true,20),
  ('employment.salary_slips','employee_name','Employee Name','text',true,false,30),
  ('employment.salary_slips','employer_name','Employer Name','text',false,false,40),
  ('employment.salary_slips','pay_period','Pay Period','text',false,false,50),
  ('employment.salary_slips','gross_salary','Gross Salary','currency',true,false,60),
  ('employment.salary_slips','total_deductions','Total Deductions','currency',true,false,70),
  ('employment.salary_slips','net_salary','Net Salary','currency',true,false,80),
  ('employment.salary_slips','holder_name','Holder Name','text',true,false,90),
  ('employment.salary_slips','issue_date','Issue Date','date',false,false,100),
  ('employment.salary_slips','notes','Notes','longtext',true,false,110),
  ('employment.experience_relieving_letters','document_title','Document Title','text',false,false,10),
  ('employment.experience_relieving_letters','employee_name','Employee Name','text',true,false,20),
  ('employment.experience_relieving_letters','employer_name','Employer Name','text',false,false,30),
  ('employment.experience_relieving_letters','designation','Designation','text',false,false,40),
  ('employment.experience_relieving_letters','employment_from','Employed From','date',false,false,50),
  ('employment.experience_relieving_letters','employment_to','Employed To','date',false,false,60),
  ('employment.experience_relieving_letters','holder_name','Holder Name','text',true,false,70),
  ('employment.experience_relieving_letters','issue_date','Issue Date','date',false,false,80),
  ('employment.experience_relieving_letters','notes','Notes','longtext',true,false,90),
  ('employment.epf_uan_documents','document_title','Document Title','text',false,false,10),
  ('employment.epf_uan_documents','uan_number','UAN Number','text',true,true,20),
  ('employment.epf_uan_documents','pf_account_number','PF Account Number','text',true,false,30),
  ('employment.epf_uan_documents','member_name','Member Name','text',true,false,40),
  ('employment.epf_uan_documents','employer_name','Employer Name','text',false,false,50),
  ('employment.epf_uan_documents','pf_balance','PF Balance','currency',true,false,60),
  ('employment.epf_uan_documents','holder_name','Holder Name','text',true,false,70),
  ('employment.epf_uan_documents','issue_date','Issue Date','date',false,false,80),
  ('employment.epf_uan_documents','notes','Notes','longtext',true,false,90),
  ('vehicle.registration_certificate','document_title','Document Title','text',false,false,10),
  ('vehicle.registration_certificate','registration_number','Registration Number','text',true,true,20),
  ('vehicle.registration_certificate','chassis_number','Chassis Number','text',true,false,30),
  ('vehicle.registration_certificate','engine_number','Engine Number','text',true,false,40),
  ('vehicle.registration_certificate','owner_name','Owner Name','text',true,false,50),
  ('vehicle.registration_certificate','vehicle_make_model','Make & Model','text',false,false,60),
  ('vehicle.registration_certificate','vehicle_class','Vehicle Class','text',false,false,70),
  ('vehicle.registration_certificate','fuel_type','Fuel Type','text',false,false,80),
  ('vehicle.registration_certificate','registration_date','Registration Date','date',false,false,90),
  ('vehicle.registration_certificate','valid_to','Valid To','date',false,false,100),
  ('vehicle.registration_certificate','holder_name','Holder Name','text',true,false,110),
  ('vehicle.registration_certificate','issue_date','Issue Date','date',false,false,120),
  ('vehicle.registration_certificate','notes','Notes','longtext',true,false,130),
  ('vehicle.puc_certificate','document_title','Document Title','text',false,false,10),
  ('vehicle.puc_certificate','certificate_number','Certificate Number','text',true,true,20),
  ('vehicle.puc_certificate','registration_number','Registration Number','text',true,false,30),
  ('vehicle.puc_certificate','testing_centre','Testing Centre','text',false,false,40),
  ('vehicle.puc_certificate','test_date','Test Date','date',false,false,50),
  ('vehicle.puc_certificate','valid_to','Valid To','date',false,false,60),
  ('vehicle.puc_certificate','holder_name','Holder Name','text',true,false,70),
  ('vehicle.puc_certificate','issue_date','Issue Date','date',false,false,80),
  ('vehicle.puc_certificate','notes','Notes','longtext',true,false,90),
  ('vehicle.purchase_invoice','document_title','Document Title','text',false,false,10),
  ('vehicle.purchase_invoice','invoice_number','Invoice Number','text',true,true,20),
  ('vehicle.purchase_invoice','chassis_number','Chassis Number','text',true,false,30),
  ('vehicle.purchase_invoice','dealer_name','Dealer Name','text',false,false,40),
  ('vehicle.purchase_invoice','vehicle_make_model','Make & Model','text',false,false,50),
  ('vehicle.purchase_invoice','invoice_amount','Invoice Amount','currency',true,false,60),
  ('vehicle.purchase_invoice','invoice_date','Invoice Date','date',false,false,70),
  ('vehicle.purchase_invoice','holder_name','Holder Name','text',true,false,80),
  ('vehicle.purchase_invoice','issue_date','Issue Date','date',false,false,90),
  ('vehicle.purchase_invoice','notes','Notes','longtext',true,false,100),
  ('vehicle.insurance_cross_ref','document_title','Document Title','text',false,false,10),
  ('vehicle.insurance_cross_ref','policy_number','Policy Number','text',true,false,20),
  ('vehicle.insurance_cross_ref','registration_number','Registration Number','text',true,false,30),
  ('vehicle.insurance_cross_ref','insurer_name','Insurer Name','text',false,false,40),
  ('vehicle.insurance_cross_ref','valid_to','Valid To','date',false,false,50),
  ('vehicle.insurance_cross_ref','holder_name','Holder Name','text',true,false,60),
  ('vehicle.insurance_cross_ref','issue_date','Issue Date','date',false,false,70),
  ('vehicle.insurance_cross_ref','notes','Notes','longtext',true,false,80),
  ('civil_government.marriage_certificate','document_title','Document Title','text',false,false,10),
  ('civil_government.marriage_certificate','registration_number','Registration Number','text',true,true,20),
  ('civil_government.marriage_certificate','spouse_names','Spouse Names','longtext',true,false,30),
  ('civil_government.marriage_certificate','place_of_marriage','Place of Marriage','text',false,false,40),
  ('civil_government.marriage_certificate','marriage_date','Marriage Date','date',false,false,50),
  ('civil_government.marriage_certificate','issuing_authority','Issuing Authority','text',false,false,60),
  ('civil_government.marriage_certificate','holder_name','Holder Name','text',true,false,70),
  ('civil_government.marriage_certificate','issue_date','Issue Date','date',false,false,80),
  ('civil_government.marriage_certificate','notes','Notes','longtext',true,false,90),
  ('civil_government.domicile_certificate','document_title','Document Title','text',false,false,10),
  ('civil_government.domicile_certificate','certificate_number','Certificate Number','text',true,true,20),
  ('civil_government.domicile_certificate','applicant_name','Applicant Name','text',true,false,30),
  ('civil_government.domicile_certificate','state_name','State','text',false,false,40),
  ('civil_government.domicile_certificate','issuing_authority','Issuing Authority','text',false,false,50),
  ('civil_government.domicile_certificate','valid_to','Valid To','date',false,false,60),
  ('civil_government.domicile_certificate','holder_name','Holder Name','text',true,false,70),
  ('civil_government.domicile_certificate','issue_date','Issue Date','date',false,false,80),
  ('civil_government.domicile_certificate','notes','Notes','longtext',true,false,90),
  ('civil_government.caste_income_certificates','document_title','Document Title','text',false,false,10),
  ('civil_government.caste_income_certificates','certificate_number','Certificate Number','text',true,true,20),
  ('civil_government.caste_income_certificates','applicant_name','Applicant Name','text',true,false,30),
  ('civil_government.caste_income_certificates','certificate_kind','Certificate Kind','text',false,false,40),
  ('civil_government.caste_income_certificates','declared_value','Caste / Declared Income','text',true,false,50),
  ('civil_government.caste_income_certificates','issuing_authority','Issuing Authority','text',false,false,60),
  ('civil_government.caste_income_certificates','valid_to','Valid To','date',false,false,70),
  ('civil_government.caste_income_certificates','holder_name','Holder Name','text',true,false,80),
  ('civil_government.caste_income_certificates','issue_date','Issue Date','date',false,false,90),
  ('civil_government.caste_income_certificates','notes','Notes','longtext',true,false,100),
  ('civil_government.senior_citizen_card','document_title','Document Title','text',false,false,10),
  ('civil_government.senior_citizen_card','card_number','Card Number','text',true,true,20),
  ('civil_government.senior_citizen_card','date_of_birth','Date of Birth','date',true,false,30),
  ('civil_government.senior_citizen_card','issuing_authority','Issuing Authority','text',false,false,40),
  ('civil_government.senior_citizen_card','valid_to','Valid To','date',false,false,50),
  ('civil_government.senior_citizen_card','holder_name','Holder Name','text',true,false,60),
  ('civil_government.senior_citizen_card','issue_date','Issue Date','date',false,false,70),
  ('civil_government.senior_citizen_card','notes','Notes','longtext',true,false,80),
  ('civil_government.oci_visa_residency','document_title','Document Title','text',false,false,10),
  ('civil_government.oci_visa_residency','document_number','Document Number','text',true,true,20),
  ('civil_government.oci_visa_residency','passport_number','Passport Number','text',true,false,30),
  ('civil_government.oci_visa_residency','document_kind','Document Kind','text',false,false,40),
  ('civil_government.oci_visa_residency','country_name','Country','text',false,false,50),
  ('civil_government.oci_visa_residency','issuing_authority','Issuing Authority','text',false,false,60),
  ('civil_government.oci_visa_residency','valid_from','Valid From','date',false,false,70),
  ('civil_government.oci_visa_residency','valid_to','Valid To','date',false,false,80),
  ('civil_government.oci_visa_residency','holder_name','Holder Name','text',true,false,90),
  ('civil_government.oci_visa_residency','issue_date','Issue Date','date',false,false,100),
  ('civil_government.oci_visa_residency','notes','Notes','longtext',true,false,110),
  ('warranty_amc.appliance_warranties','document_title','Document Title','text',false,false,10),
  ('warranty_amc.appliance_warranties','serial_number','Serial Number','text',true,true,20),
  ('warranty_amc.appliance_warranties','product_name','Product','text',false,false,30),
  ('warranty_amc.appliance_warranties','brand_name','Brand','text',false,false,40),
  ('warranty_amc.appliance_warranties','dealer_name','Dealer','text',false,false,50),
  ('warranty_amc.appliance_warranties','purchase_date','Purchase Date','date',false,false,60),
  ('warranty_amc.appliance_warranties','warranty_months','Warranty (Months)','number',false,false,70),
  ('warranty_amc.appliance_warranties','warranty_expiry','Warranty Expiry','date',false,false,80),
  ('warranty_amc.appliance_warranties','holder_name','Holder Name','text',true,false,90),
  ('warranty_amc.appliance_warranties','issue_date','Issue Date','date',false,false,100),
  ('warranty_amc.appliance_warranties','notes','Notes','longtext',true,false,110),
  ('warranty_amc.amc_contracts','document_title','Document Title','text',false,false,10),
  ('warranty_amc.amc_contracts','contract_number','Contract Number','text',true,true,20),
  ('warranty_amc.amc_contracts','service_provider','Service Provider','text',false,false,30),
  ('warranty_amc.amc_contracts','asset_covered','Asset Covered','text',false,false,40),
  ('warranty_amc.amc_contracts','contract_amount','Contract Amount','currency',true,false,50),
  ('warranty_amc.amc_contracts','valid_from','Valid From','date',false,false,60),
  ('warranty_amc.amc_contracts','valid_to','Valid To','date',false,false,70),
  ('warranty_amc.amc_contracts','holder_name','Holder Name','text',true,false,80),
  ('warranty_amc.amc_contracts','issue_date','Issue Date','date',false,false,90),
  ('warranty_amc.amc_contracts','notes','Notes','longtext',true,false,100),
  ('rentals_subscriptions.rental_agreements','document_title','Document Title','text',false,false,10),
  ('rentals_subscriptions.rental_agreements','agreement_number','Agreement Number','text',true,false,20),
  ('rentals_subscriptions.rental_agreements','property_address','Property Address','longtext',true,false,30),
  ('rentals_subscriptions.rental_agreements','landlord_name','Landlord Name','text',true,false,40),
  ('rentals_subscriptions.rental_agreements','tenant_name','Tenant Name','text',true,false,50),
  ('rentals_subscriptions.rental_agreements','monthly_rent','Monthly Rent','currency',true,false,60),
  ('rentals_subscriptions.rental_agreements','deposit_amount','Security Deposit','currency',true,false,70),
  ('rentals_subscriptions.rental_agreements','lease_from','Lease From','date',false,false,80),
  ('rentals_subscriptions.rental_agreements','lease_to','Lease To','date',false,false,90),
  ('rentals_subscriptions.rental_agreements','holder_name','Holder Name','text',true,false,100),
  ('rentals_subscriptions.rental_agreements','issue_date','Issue Date','date',false,false,110),
  ('rentals_subscriptions.rental_agreements','notes','Notes','longtext',true,false,120),
  ('rentals_subscriptions.subscription_receipts','document_title','Document Title','text',false,false,10),
  ('rentals_subscriptions.subscription_receipts','subscription_id','Subscription ID','text',true,true,20),
  ('rentals_subscriptions.subscription_receipts','service_name','Service','text',false,false,30),
  ('rentals_subscriptions.subscription_receipts','plan_name','Plan','text',false,false,40),
  ('rentals_subscriptions.subscription_receipts','billing_cycle','Billing Cycle','text',false,false,50),
  ('rentals_subscriptions.subscription_receipts','amount_paid','Amount Paid','currency',true,false,60),
  ('rentals_subscriptions.subscription_receipts','renewal_due_date','Renewal Due Date','date',false,false,70),
  ('rentals_subscriptions.subscription_receipts','holder_name','Holder Name','text',true,false,80),
  ('rentals_subscriptions.subscription_receipts','issue_date','Issue Date','date',false,false,90),
  ('rentals_subscriptions.subscription_receipts','notes','Notes','longtext',true,false,100),
  ('utility_bills.electricity','document_title','Document Title','text',false,false,10),
  ('utility_bills.electricity','consumer_number','Consumer Number','text',true,true,20),
  ('utility_bills.electricity','provider_name','Provider','text',false,false,30),
  ('utility_bills.electricity','service_address','Service Address','longtext',true,false,40),
  ('utility_bills.electricity','billing_period','Billing Period','text',false,false,50),
  ('utility_bills.electricity','units_consumed','Units Consumed','number',false,false,60),
  ('utility_bills.electricity','bill_amount','Bill Amount','currency',true,false,70),
  ('utility_bills.electricity','due_date','Due Date','date',false,false,80),
  ('utility_bills.electricity','holder_name','Holder Name','text',true,false,90),
  ('utility_bills.electricity','issue_date','Issue Date','date',false,false,100),
  ('utility_bills.electricity','notes','Notes','longtext',true,false,110),
  ('utility_bills.gas','document_title','Document Title','text',false,false,10),
  ('utility_bills.gas','consumer_number','Consumer Number','text',true,true,20),
  ('utility_bills.gas','provider_name','Provider','text',false,false,30),
  ('utility_bills.gas','connection_type','Connection Type','text',false,false,40),
  ('utility_bills.gas','billing_period','Billing Period','text',false,false,50),
  ('utility_bills.gas','bill_amount','Bill Amount','currency',true,false,60),
  ('utility_bills.gas','due_date','Due Date','date',false,false,70),
  ('utility_bills.gas','holder_name','Holder Name','text',true,false,80),
  ('utility_bills.gas','issue_date','Issue Date','date',false,false,90),
  ('utility_bills.gas','notes','Notes','longtext',true,false,100),
  ('utility_bills.water','document_title','Document Title','text',false,false,10),
  ('utility_bills.water','consumer_number','Consumer Number','text',true,true,20),
  ('utility_bills.water','provider_name','Provider','text',false,false,30),
  ('utility_bills.water','billing_period','Billing Period','text',false,false,40),
  ('utility_bills.water','bill_amount','Bill Amount','currency',true,false,50),
  ('utility_bills.water','due_date','Due Date','date',false,false,60),
  ('utility_bills.water','holder_name','Holder Name','text',true,false,70),
  ('utility_bills.water','issue_date','Issue Date','date',false,false,80),
  ('utility_bills.water','notes','Notes','longtext',true,false,90),
  ('tax_compliance.tds_certificates','document_title','Document Title','text',false,false,10),
  ('tax_compliance.tds_certificates','certificate_number','Certificate Number','text',true,true,20),
  ('tax_compliance.tds_certificates','pan_number','PAN Number','text',true,false,30),
  ('tax_compliance.tds_certificates','deductor_tan','Deductor TAN','text',true,false,40),
  ('tax_compliance.tds_certificates','deductor_name','Deductor Name','text',false,false,50),
  ('tax_compliance.tds_certificates','form_kind','Form Kind','text',false,false,60),
  ('tax_compliance.tds_certificates','assessment_year','Assessment Year','text',false,false,70),
  ('tax_compliance.tds_certificates','tds_amount','TDS Amount','currency',true,false,80),
  ('tax_compliance.tds_certificates','holder_name','Holder Name','text',true,false,90),
  ('tax_compliance.tds_certificates','issue_date','Issue Date','date',false,false,100),
  ('tax_compliance.tds_certificates','notes','Notes','longtext',true,false,110),
  ('tax_compliance.advance_tax_receipts','document_title','Document Title','text',false,false,10),
  ('tax_compliance.advance_tax_receipts','challan_number','Challan Number','text',true,true,20),
  ('tax_compliance.advance_tax_receipts','pan_number','PAN Number','text',true,false,30),
  ('tax_compliance.advance_tax_receipts','bank_name','Bank Name','text',false,false,40),
  ('tax_compliance.advance_tax_receipts','assessment_year','Assessment Year','text',false,false,50),
  ('tax_compliance.advance_tax_receipts','amount_paid','Amount Paid','currency',true,false,60),
  ('tax_compliance.advance_tax_receipts','payment_date','Payment Date','date',false,false,70),
  ('tax_compliance.advance_tax_receipts','holder_name','Holder Name','text',true,false,80),
  ('tax_compliance.advance_tax_receipts','issue_date','Issue Date','date',false,false,90),
  ('tax_compliance.advance_tax_receipts','notes','Notes','longtext',true,false,100),
  ('tax_compliance.wealth_asset_declarations','document_title','Document Title','text',false,false,10),
  ('tax_compliance.wealth_asset_declarations','declaration_number','Declaration Number','text',true,false,20),
  ('tax_compliance.wealth_asset_declarations','pan_number','PAN Number','text',true,false,30),
  ('tax_compliance.wealth_asset_declarations','assessment_year','Assessment Year','text',false,false,40),
  ('tax_compliance.wealth_asset_declarations','total_assets_value','Total Assets Value','currency',true,false,50),
  ('tax_compliance.wealth_asset_declarations','total_liabilities_value','Total Liabilities Value','currency',true,false,60),
  ('tax_compliance.wealth_asset_declarations','asset_details','Asset Details','longtext',true,false,70),
  ('tax_compliance.wealth_asset_declarations','holder_name','Holder Name','text',true,false,80),
  ('tax_compliance.wealth_asset_declarations','issue_date','Issue Date','date',false,false,90),
  ('tax_compliance.wealth_asset_declarations','notes','Notes','longtext',true,false,100),
  ('tax_compliance.pension_payment_order','document_title','Document Title','text',false,false,10),
  ('tax_compliance.pension_payment_order','ppo_number','PPO Number','text',true,true,20),
  ('tax_compliance.pension_payment_order','pensioner_name','Pensioner Name','text',true,false,30),
  ('tax_compliance.pension_payment_order','bank_account_number','Bank Account Number','text',true,false,40),
  ('tax_compliance.pension_payment_order','disbursing_authority','Disbursing Authority','text',false,false,50),
  ('tax_compliance.pension_payment_order','monthly_pension','Monthly Pension','currency',true,false,60),
  ('tax_compliance.pension_payment_order','retirement_date','Retirement Date','date',false,false,70),
  ('tax_compliance.pension_payment_order','holder_name','Holder Name','text',true,false,80),
  ('tax_compliance.pension_payment_order','issue_date','Issue Date','date',false,false,90),
  ('tax_compliance.pension_payment_order','notes','Notes','longtext',true,false,100),
  ('business.registration_certificate','document_title','Document Title','text',false,false,10),
  ('business.registration_certificate','registration_number','Registration Number','text',true,true,20),
  ('business.registration_certificate','business_name','Business Name','text',false,false,30),
  ('business.registration_certificate','registration_kind','Registration Kind','text',false,false,40),
  ('business.registration_certificate','issuing_authority','Issuing Authority','text',false,false,50),
  ('business.registration_certificate','valid_to','Valid To','date',false,false,60),
  ('business.registration_certificate','holder_name','Holder Name','text',true,false,70),
  ('business.registration_certificate','issue_date','Issue Date','date',false,false,80),
  ('business.registration_certificate','notes','Notes','longtext',true,false,90),
  ('business.partnership_deed_moa_aoa','document_title','Document Title','text',false,false,10),
  ('business.partnership_deed_moa_aoa','cin_or_llpin','CIN / LLPIN','text',true,true,20),
  ('business.partnership_deed_moa_aoa','entity_name','Entity Name','text',false,false,30),
  ('business.partnership_deed_moa_aoa','partner_names','Partners / Directors','longtext',true,false,40),
  ('business.partnership_deed_moa_aoa','capital_contribution','Capital Contribution','currency',true,false,50),
  ('business.partnership_deed_moa_aoa','incorporation_date','Incorporation Date','date',false,false,60),
  ('business.partnership_deed_moa_aoa','holder_name','Holder Name','text',true,false,70),
  ('business.partnership_deed_moa_aoa','issue_date','Issue Date','date',false,false,80),
  ('business.partnership_deed_moa_aoa','notes','Notes','longtext',true,false,90),
  ('business.gst_registration_certificate','document_title','Document Title','text',false,false,10),
  ('business.gst_registration_certificate','gstin','GSTIN','text',true,true,20),
  ('business.gst_registration_certificate','legal_business_name','Legal Business Name','text',false,false,30),
  ('business.gst_registration_certificate','trade_name','Trade Name','text',false,false,40),
  ('business.gst_registration_certificate','taxpayer_kind','Taxpayer Kind','text',false,false,50),
  ('business.gst_registration_certificate','principal_place','Principal Place of Business','longtext',true,false,60),
  ('business.gst_registration_certificate','registration_date','Registration Date','date',false,false,70),
  ('business.gst_registration_certificate','holder_name','Holder Name','text',true,false,80),
  ('business.gst_registration_certificate','issue_date','Issue Date','date',false,false,90),
  ('business.gst_registration_certificate','notes','Notes','longtext',true,false,100),
  ('business.gst_returns','document_title','Document Title','text',false,false,10),
  ('business.gst_returns','gstin','GSTIN','text',true,true,20),
  ('business.gst_returns','arn_number','ARN','text',true,false,30),
  ('business.gst_returns','return_kind','Return Kind','text',false,false,40),
  ('business.gst_returns','return_period','Return Period','text',false,false,50),
  ('business.gst_returns','taxable_value','Taxable Value','currency',true,false,60),
  ('business.gst_returns','tax_payable','Tax Payable','currency',true,false,70),
  ('business.gst_returns','filing_date','Filing Date','date',false,false,80),
  ('business.gst_returns','holder_name','Holder Name','text',true,false,90),
  ('business.gst_returns','issue_date','Issue Date','date',false,false,100),
  ('business.gst_returns','notes','Notes','longtext',true,false,110),
  ('business.pan_tan','document_title','Document Title','text',false,false,10),
  ('business.pan_tan','pan_number','Business PAN','text',true,true,20),
  ('business.pan_tan','tan_number','TAN','text',true,false,30),
  ('business.pan_tan','entity_name','Entity Name','text',false,false,40),
  ('business.pan_tan','issuing_authority','Issuing Authority','text',false,false,50),
  ('business.pan_tan','holder_name','Holder Name','text',true,false,60),
  ('business.pan_tan','issue_date','Issue Date','date',false,false,70),
  ('business.pan_tan','notes','Notes','longtext',true,false,80),
  ('business.import_export_code','document_title','Document Title','text',false,false,10),
  ('business.import_export_code','iec_code','Import Export Code','text',true,true,20),
  ('business.import_export_code','entity_name','Entity Name','text',false,false,30),
  ('business.import_export_code','branch_details','Branch Details','longtext',true,false,40),
  ('business.import_export_code','issuing_authority','Issuing Authority','text',false,false,50),
  ('business.import_export_code','holder_name','Holder Name','text',true,false,60),
  ('business.import_export_code','issue_date','Issue Date','date',false,false,70),
  ('business.import_export_code','notes','Notes','longtext',true,false,80),
  ('business.professional_tax_registration','document_title','Document Title','text',false,false,10),
  ('business.professional_tax_registration','registration_number','Registration Number','text',true,true,20),
  ('business.professional_tax_registration','entity_name','Entity Name','text',false,false,30),
  ('business.professional_tax_registration','state_name','State','text',false,false,40),
  ('business.professional_tax_registration','issuing_authority','Issuing Authority','text',false,false,50),
  ('business.professional_tax_registration','holder_name','Holder Name','text',true,false,60),
  ('business.professional_tax_registration','issue_date','Issue Date','date',false,false,70),
  ('business.professional_tax_registration','notes','Notes','longtext',true,false,80),
  ('business.trademark_ip_registration','document_title','Document Title','text',false,false,10),
  ('business.trademark_ip_registration','application_number','Application Number','text',true,true,20),
  ('business.trademark_ip_registration','mark_name','Mark / Title','text',false,false,30),
  ('business.trademark_ip_registration','ip_class','Class','text',false,false,40),
  ('business.trademark_ip_registration','registry_office','Registry Office','text',false,false,50),
  ('business.trademark_ip_registration','registration_date','Registration Date','date',false,false,60),
  ('business.trademark_ip_registration','valid_to','Valid To','date',false,false,70),
  ('business.trademark_ip_registration','holder_name','Holder Name','text',true,false,80),
  ('business.trademark_ip_registration','issue_date','Issue Date','date',false,false,90),
  ('business.trademark_ip_registration','notes','Notes','longtext',true,false,100),
  ('business.bank_statements','document_title','Document Title','text',false,false,10),
  ('business.bank_statements','account_number','Account Number','text',true,true,20),
  ('business.bank_statements','ifsc_code','IFSC Code','text',true,false,30),
  ('business.bank_statements','bank_name','Bank Name','text',false,false,40),
  ('business.bank_statements','entity_name','Entity Name','text',false,false,50),
  ('business.bank_statements','statement_period','Statement Period','text',false,false,60),
  ('business.bank_statements','closing_balance','Closing Balance','currency',true,false,70),
  ('business.bank_statements','holder_name','Holder Name','text',true,false,80),
  ('business.bank_statements','issue_date','Issue Date','date',false,false,90),
  ('business.bank_statements','notes','Notes','longtext',true,false,100),
  ('business.loan_working_capital','document_title','Document Title','text',false,false,10),
  ('business.loan_working_capital','loan_account_number','Loan Account Number','text',true,true,20),
  ('business.loan_working_capital','lender_name','Lender Name','text',false,false,30),
  ('business.loan_working_capital','facility_kind','Facility Kind','text',false,false,40),
  ('business.loan_working_capital','sanctioned_amount','Sanctioned Amount','currency',true,false,50),
  ('business.loan_working_capital','interest_rate','Interest Rate (%)','number',false,false,60),
  ('business.loan_working_capital','sanction_date','Sanction Date','date',false,false,70),
  ('business.loan_working_capital','holder_name','Holder Name','text',true,false,80),
  ('business.loan_working_capital','issue_date','Issue Date','date',false,false,90),
  ('business.loan_working_capital','notes','Notes','longtext',true,false,100),
  ('business.insurance','document_title','Document Title','text',false,false,10),
  ('business.insurance','policy_number','Policy Number','text',true,true,20),
  ('business.insurance','insurer_name','Insurer Name','text',false,false,30),
  ('business.insurance','coverage_type','Coverage Type','text',false,false,40),
  ('business.insurance','sum_insured','Sum Insured','currency',true,false,50),
  ('business.insurance','premium_amount','Premium Amount','currency',true,false,60),
  ('business.insurance','valid_to','Valid To','date',false,false,70),
  ('business.insurance','holder_name','Holder Name','text',true,false,80),
  ('business.insurance','issue_date','Issue Date','date',false,false,90),
  ('business.insurance','notes','Notes','longtext',true,false,100),
  ('business.roc_mca_filings','document_title','Document Title','text',false,false,10),
  ('business.roc_mca_filings','cin_number','CIN','text',true,true,20),
  ('business.roc_mca_filings','srn_number','SRN','text',true,false,30),
  ('business.roc_mca_filings','entity_name','Entity Name','text',false,false,40),
  ('business.roc_mca_filings','form_kind','Form Kind','text',false,false,50),
  ('business.roc_mca_filings','financial_year','Financial Year','text',false,false,60),
  ('business.roc_mca_filings','filing_date','Filing Date','date',false,false,70),
  ('business.roc_mca_filings','holder_name','Holder Name','text',true,false,80),
  ('business.roc_mca_filings','issue_date','Issue Date','date',false,false,90),
  ('business.roc_mca_filings','notes','Notes','longtext',true,false,100),
  ('business.audited_financials','document_title','Document Title','text',false,false,10),
  ('business.audited_financials','entity_name','Entity Name','text',false,false,20),
  ('business.audited_financials','auditor_name','Auditor','text',false,false,30),
  ('business.audited_financials','financial_year','Financial Year','text',false,false,40),
  ('business.audited_financials','total_revenue','Total Revenue','currency',true,false,50),
  ('business.audited_financials','net_profit','Net Profit','currency',true,false,60),
  ('business.audited_financials','total_assets','Total Assets','currency',true,false,70),
  ('business.audited_financials','holder_name','Holder Name','text',true,false,80),
  ('business.audited_financials','issue_date','Issue Date','date',false,false,90),
  ('business.audited_financials','notes','Notes','longtext',true,false,100),
  ('business.employer_statutory_registrations','document_title','Document Title','text',false,false,10),
  ('business.employer_statutory_registrations','registration_number','Registration Number','text',true,true,20),
  ('business.employer_statutory_registrations','scheme_type','Scheme (PF / ESI)','text',false,false,30),
  ('business.employer_statutory_registrations','entity_name','Entity Name','text',false,false,40),
  ('business.employer_statutory_registrations','employee_count','Employee Count','number',true,false,50),
  ('business.employer_statutory_registrations','issuing_authority','Issuing Authority','text',false,false,60),
  ('business.employer_statutory_registrations','holder_name','Holder Name','text',true,false,70),
  ('business.employer_statutory_registrations','issue_date','Issue Date','date',false,false,80),
  ('business.employer_statutory_registrations','notes','Notes','longtext',true,false,90),
  ('business.client_vendor_contracts','document_title','Document Title','text',false,false,10),
  ('business.client_vendor_contracts','contract_number','Contract Number','text',true,true,20),
  ('business.client_vendor_contracts','counterparty_name','Counterparty Name','text',true,false,30),
  ('business.client_vendor_contracts','contract_kind','Contract Kind','text',false,false,40),
  ('business.client_vendor_contracts','contract_value','Contract Value','currency',true,false,50),
  ('business.client_vendor_contracts','key_terms','Key Terms','longtext',true,false,60),
  ('business.client_vendor_contracts','valid_from','Valid From','date',false,false,70),
  ('business.client_vendor_contracts','valid_to','Valid To','date',false,false,80),
  ('business.client_vendor_contracts','holder_name','Holder Name','text',true,false,90),
  ('business.client_vendor_contracts','issue_date','Issue Date','date',false,false,100),
  ('business.client_vendor_contracts','notes','Notes','longtext',true,false,110),
  ('business.invoices','document_title','Document Title','text',false,false,10),
  ('business.invoices','invoice_number','Invoice Number','text',true,true,20),
  ('business.invoices','counterparty_name','Counterparty Name','text',true,false,30),
  ('business.invoices','gstin','GSTIN','text',true,false,40),
  ('business.invoices','taxable_value','Taxable Value','currency',true,false,50),
  ('business.invoices','tax_amount','Tax Amount','currency',true,false,60),
  ('business.invoices','total_amount','Total Amount','currency',true,false,70),
  ('business.invoices','payment_status','Payment Status','text',false,false,80),
  ('business.invoices','invoice_date','Invoice Date','date',false,false,90),
  ('business.invoices','holder_name','Holder Name','text',true,false,100),
  ('business.invoices','issue_date','Issue Date','date',false,false,110),
  ('business.invoices','notes','Notes','longtext',true,false,120),
  ('system.uncategorized','document_title','Document Title','text',false,false,10),
  ('system.uncategorized','holder_name','Holder Name','text',true,false,20),
  ('system.uncategorized','issue_date','Issue Date','date',false,false,30),
  ('system.uncategorized','notes','Notes','longtext',true,false,40)
) AS v(code, field_key, field_label, data_type, is_pii, is_required, sort_order)
JOIN "document_categories" dc ON dc.code = v.code
ON CONFLICT (category_id, field_key) WHERE tenant_id IS NULL DO NOTHING;

-- POST-CHECKS (run manually after applying; not part of the migration):
--   SELECT count(*) FROM document_category_fields WHERE tenant_id IS NULL;  -- 820
--   SELECT count(*) FROM document_categories dc WHERE NOT EXISTS
--     (SELECT 1 FROM document_category_fields f WHERE f.category_id = dc.id);  -- 0
