import { randomUUID } from 'crypto';
import type { CategoryKey } from '../documentCategories';
import { db } from '../db';
import { identifierFields } from '../documentCategoryFields';
import { loadCategoryFieldSpec } from '../records/categorySpec';
import { resolveModuleCategory } from './moduleCategoryMap';
import { type RecordVaultColumns, storeRecordInVault } from './vaultStore';
import { toTaxonomyRecord } from '../records/normalize';

/**
 * The one call a page's route makes to put a file in the vault.
 *
 * Wraps category resolution and `storeRecordInVault` so each of the eleven
 * non-document pages changes by two lines rather than twenty. Replaces a
 * `saveUploadedFile(file, user.tenant)` call:
 *
 *   const recordId = randomUUID();
 *   const vault = await storeModuleFile({
 *     scope: 'medical', user, recordId, file, record: parsedBody,
 *   });
 *   // then spread `vault` into the insert alongside the page's own columns
 *
 * Currently unused — every write goes through `uploadRecords` since the record
 * consolidation. Kept because it is the documented seam for a route that needs
 * to seal a single file without the batch pipeline, and kept in step with that
 * pipeline for the same reason: a seam that has drifted is worse than no seam.
 *
 * It does NOT run the duplicate check `createRecord` runs, so a route reaching
 * for it is choosing to file whatever it is given.
 *
 * The record id is generated by the caller so the same value can be used as the
 * row's primary key, the Drive filename and the JSON store key — the three have
 * to agree or the file cannot be found again.
 */

export interface StoreModuleFileInput {
  /** The company this upload belongs to, or null/absent for a personal record. */
  companyId?: string | null;
  /**
   * The record SCOPE — the page. It picks the `recordType` translation and the
   * legacy field map, and appears in the record's `filePath`. The vault module
   * follows the resolved category, not this. See vaultStore.ts.
   */
  scope: string;
  /** The authenticated user, carrying `tenant`, `tenantId` and `id`. */
  user: any;
  /** Pre-generated id, also used as the row's primary key. */
  recordId: string;
  file: File;
  /** Who the record belongs to. Defaults to the uploading user. */
  ownerId?: string;
  holderId?: string | null;
  isGlobal?: boolean;
  /** Display name for the record, used in the JSON store. */
  name?: string;
  /**
   * The parsed record body. Two jobs: its type field picks the category, and
   * its fields are split into open/sealed by the category's encryption policy.
   */
  record?: Record<string, unknown> | null;
  /** An explicitly chosen category, if the module has a picker. */
  categoryKey?: Partial<CategoryKey> | null;
  /** Replace flow — overwrite this Drive file rather than creating another. */
  existingFileId?: string | null;
}

export async function storeModuleFile(
  input: StoreModuleFileInput
): Promise<RecordVaultColumns> {
  const { scope, user, recordId, file, record } = input;

  // Resolved from the LEGACY body, because the type field that picks the
  // category (`policyType`, `formType`, `loanType`, …) is itself a legacy name.
  const categoryKey = resolveModuleCategory(scope, record, input.categoryKey);

  // Then, and only then, rename the keys. `splitRecordFields` seals by matching
  // the record's keys against the category's encrypt list, and that list is
  // snake_case taxonomy fieldKeys while `record` is the camelCase form body —
  // so without this the intersection is empty and NOTHING is ever sealed.
  //
  // WITH the category's effective spec and identifiers, as `createRecord` and
  // `updateRecordInVault` both do. The spec is operator-editable, and it
  // decides which key a mapping resolves to and which values get a blind index;
  // renaming against the compiled dictionary here would file a record under
  // different keys than every other write path uses for the same category.
  const specs = await loadCategoryFieldSpec(db, categoryKey);
  const normalized = toTaxonomyRecord(
    scope, categoryKey, record, identifierFields(specs), specs,
  );

  const bytes = Buffer.from(await file.arrayBuffer());

  return await storeRecordInVault({
    scope,
    tenant: user.tenant,
    tenantId: user.tenantId,
    companyId: input.companyId ?? null,
    actorUserId: user.id,
    ownerId: input.ownerId ?? user.id,
    holderId: input.holderId ?? null,
    isGlobal: input.isGlobal ?? false,
    recordId,
    categoryKey,
    name: input.name || file.name || 'Untitled',
    bytes,
    fileName: file.name,
    mimeType: file.type,
    fileSize: file.size,
    metadata: normalized.record,
    searchHashes: normalized.searchHashes,
    masked: normalized.masked,
    reminders: normalized.reminders,
    // The keys the field map ASSERTS are PII, which `uploadRecords` passes and
    // this omitted: without it a `seal: true` value landing on a key the
    // category does not declare reaches the open tier in the clear.
    mustSeal: normalized.mustSeal,
    existingFileId: input.existingFileId,
  });
}

/** Convenience for routes that let the helper mint the id. */
export function newRecordId(): string {
  return randomUUID();
}
