-- ═══════════════════════════════════════════════════════════════════════════
--  PREVIOUS CONTENTS of document_categories + document_category_fields
--  State as of migration 0014, i.e. immediately BEFORE 0015_taxonomy_reshuffle.
--  14 taxonomy modules + the 'system' fallback = 83 categories.
--  Column shape is post-0012 (module_key + document_key, document_name).
--  Reference only — restoring this would re-break the module vocabulary and
--  strand vault ciphertext whose AAD binds the CURRENT module_key.
-- ═══════════════════════════════════════════════════════════════════════════

-- ── document_categories ────────────────────────────────────────────────────
-- module_key | document_key | module_no | module_name | document_name | sort_order | is_system | is_active
INSERT INTO "document_categories"
  ("tenant_id","module_key","document_key","module_no","module_name","document_name","sort_order","is_system","is_active")
VALUES
  (NULL,'identity','aadhaar_card',1,'Identity','Aadhaar Card (all members)',1001,true,true),
  (NULL,'identity','pan_card',1,'Identity','PAN Card',1002,true,true),
  (NULL,'identity','passport',1,'Identity','Passport',1003,true,true),
  (NULL,'identity','voter_id',1,'Identity','Voter ID',1004,true,true),
  (NULL,'identity','driving_license',1,'Identity','Driving License',1005,true,true),
  (NULL,'identity','birth_certificate',1,'Identity','Birth Certificate',1006,true,true),
  (NULL,'identity','death_certificate',1,'Identity','Death Certificate',1007,true,true),
  (NULL,'identity','ration_card',1,'Identity','Ration Card',1008,true,true),
  (NULL,'bank_investments','bank_statements_passbooks',2,'Bank & Investments','Bank account statements / passbooks',2001,true,true),
  (NULL,'bank_investments','fixed_deposit_receipts',2,'Bank & Investments','Fixed Deposit receipts',2002,true,true),
  (NULL,'bank_investments','mutual_fund_statements',2,'Bank & Investments','Mutual fund statements',2003,true,true),
  (NULL,'bank_investments','demat_trading_documents',2,'Bank & Investments','Demat / trading account documents',2004,true,true),
  (NULL,'bank_investments','loan_agreements',2,'Bank & Investments','Loan agreements (home, personal, vehicle, education)',2005,true,true),
  (NULL,'bank_investments','credit_card_statements',2,'Bank & Investments','Credit card statements',2006,true,true),
  (NULL,'bank_investments','itr_form16',2,'Bank & Investments','ITR filings and Form 16',2007,true,true),
  (NULL,'bank_investments','epf_ppf_nps_statements',2,'Bank & Investments','EPF / PPF / NPS statements',2008,true,true),
  (NULL,'bank_investments','cheque_books',2,'Bank & Investments','Cheque books, cancelled cheques',2009,true,true),
  (NULL,'bank_investments','bank_locker_agreement',2,'Bank & Investments','Bank locker agreement and inventory list',2010,true,true),
  (NULL,'insurance','life_policies',3,'Insurance','Life insurance policies',3001,true,true),
  (NULL,'insurance','health_policies',3,'Insurance','Health insurance policies (individual + family floater)',3002,true,true),
  (NULL,'insurance','vehicle_policies',3,'Insurance','Vehicle insurance',3003,true,true),
  (NULL,'insurance','home_property_policies',3,'Insurance','Home / property insurance',3004,true,true),
  (NULL,'insurance','term_policies',3,'Insurance','Term insurance',3005,true,true),
  (NULL,'insurance','premium_receipts',3,'Insurance','Policy premium receipts',3006,true,true),
  (NULL,'property_legal','sale_deed_title',4,'Property & Legal','Sale deed / property title documents',4001,true,true),
  (NULL,'property_legal','registration_stamp_duty_receipts',4,'Property & Legal','Registration and stamp duty receipts',4002,true,true),
  (NULL,'property_legal','encumbrance_certificate',4,'Property & Legal','Encumbrance certificate',4003,true,true),
  (NULL,'property_legal','property_tax_receipts',4,'Property & Legal','Property tax receipts',4004,true,true),
  (NULL,'property_legal','will_nomination',4,'Property & Legal','Will / nomination documents',4005,true,true),
  (NULL,'property_legal','power_of_attorney',4,'Property & Legal','Power of attorney',4006,true,true),
  (NULL,'property_legal','khata_mutation_certificates',4,'Property & Legal','Khata / mutation certificates (state-specific land records)',4007,true,true),
  (NULL,'property_legal','divorce_custody',4,'Property & Legal','Divorce decree / custody documents',4008,true,true),
  (NULL,'education','marksheets_certificates',5,'Education','Mark sheets and certificates (school, college)',5001,true,true),
  (NULL,'education','degree_diploma',5,'Education','Degree / diploma certificates',5002,true,true),
  (NULL,'education','migration_transfer',5,'Education','Migration and transfer certificates',5003,true,true),
  (NULL,'education','entrance_exam_scorecards',5,'Education','Entrance exam scorecards',5004,true,true),
  (NULL,'health_medical','records_prescriptions',6,'Health & Medical','Medical records and prescriptions',6001,true,true),
  (NULL,'health_medical','vaccination_certificates',6,'Health & Medical','Vaccination certificates',6002,true,true),
  (NULL,'health_medical','checkup_reports',6,'Health & Medical','Health check-up reports',6003,true,true),
  (NULL,'health_medical','discharge_summaries',6,'Health & Medical','Hospital discharge summaries',6004,true,true),
  (NULL,'health_medical','insurance_claims',6,'Health & Medical','Health insurance claim documents',6005,true,true),
  (NULL,'health_medical','disability_certificate',6,'Health & Medical','Disability certificate',6006,true,true),
  (NULL,'employment','offer_appointment_letters',7,'Employment','Offer / appointment letters',7001,true,true),
  (NULL,'employment','salary_slips',7,'Employment','Salary slips',7002,true,true),
  (NULL,'employment','experience_relieving_letters',7,'Employment','Experience / relieving letters',7003,true,true),
  (NULL,'employment','epf_uan_documents',7,'Employment','EPF UAN documents',7004,true,true),
  (NULL,'vehicle','registration_certificate',8,'Vehicle','RC (Registration Certificate)',8001,true,true),
  (NULL,'vehicle','puc_certificate',8,'Vehicle','PUC certificate',8002,true,true),
  (NULL,'vehicle','purchase_invoice',8,'Vehicle','Purchase invoice',8003,true,true),
  (NULL,'vehicle','insurance_cross_ref',8,'Vehicle','Vehicle insurance — see Insurance module',8004,true,true),
  (NULL,'civil_government','marriage_certificate',9,'Civil & Government Records','Marriage certificate',9001,true,true),
  (NULL,'civil_government','domicile_certificate',9,'Civil & Government Records','Domicile certificate',9002,true,true),
  (NULL,'civil_government','caste_income_certificates',9,'Civil & Government Records','Caste / income certificates',9003,true,true),
  (NULL,'civil_government','senior_citizen_card',9,'Civil & Government Records','Senior citizen card',9004,true,true),
  (NULL,'civil_government','oci_visa_residency',9,'Civil & Government Records','OCI card / visa / residency permits (NRI documents)',9005,true,true),
  (NULL,'warranty_amc','appliance_warranties',10,'Warranty & AMC','Appliance warranties',10001,true,true),
  (NULL,'warranty_amc','amc_contracts',10,'Warranty & AMC','AMC contracts',10002,true,true),
  (NULL,'rentals_subscriptions','rental_agreements',11,'Rentals & Subscriptions','Rental agreements',11001,true,true),
  (NULL,'rentals_subscriptions','subscription_receipts',11,'Rentals & Subscriptions','Subscription receipts / contracts (OTT, SaaS, gym, etc.)',11002,true,true),
  (NULL,'utility_bills','electricity',12,'Utility Bills','Electricity bills',12001,true,true),
  (NULL,'utility_bills','gas',12,'Utility Bills','Gas bills',12002,true,true),
  (NULL,'utility_bills','water',12,'Utility Bills','Water bills',12003,true,true),
  (NULL,'tax_compliance','tds_certificates',13,'Tax & Compliance','TDS certificates (Form 16A, 26AS)',13001,true,true),
  (NULL,'tax_compliance','advance_tax_receipts',13,'Tax & Compliance','Advance tax payment receipts',13002,true,true),
  (NULL,'tax_compliance','wealth_asset_declarations',13,'Tax & Compliance','Wealth / asset declaration documents',13003,true,true),
  (NULL,'tax_compliance','pension_payment_order',13,'Tax & Compliance','Pension Payment Order (PPO) / retirement pension statements',13004,true,true),
  (NULL,'business','registration_certificate',14,'Business','Business registration certificate (Shop & Establishment / Udyam-MSME)',14001,true,true),
  (NULL,'business','partnership_deed_moa_aoa',14,'Business','Partnership deed / MOA & AOA (for LLP / Pvt Ltd)',14002,true,true),
  (NULL,'business','gst_registration_certificate',14,'Business','GST registration certificate',14003,true,true),
  (NULL,'business','gst_returns',14,'Business','GST returns (GSTR filings)',14004,true,true),
  (NULL,'business','pan_tan',14,'Business','Business PAN / TAN',14005,true,true),
  (NULL,'business','import_export_code',14,'Business','Import Export Code (IEC), if applicable',14006,true,true),
  (NULL,'business','professional_tax_registration',14,'Business','Professional tax registration',14007,true,true),
  (NULL,'business','trademark_ip_registration',14,'Business','Trademark / IP registration',14008,true,true),
  (NULL,'business','bank_statements',14,'Business','Business bank statements',14009,true,true),
  (NULL,'business','loan_working_capital',14,'Business','Business loan / working capital documents',14010,true,true),
  (NULL,'business','insurance',14,'Business','Business insurance (fire, liability, key-man)',14011,true,true),
  (NULL,'business','roc_mca_filings',14,'Business','ROC / MCA annual filings (for registered companies)',14012,true,true),
  (NULL,'business','audited_financials',14,'Business','Audited financials / balance sheets',14013,true,true),
  (NULL,'business','employer_statutory_registrations',14,'Business','Employer statutory registrations (PF/ESI)',14014,true,true),
  (NULL,'business','client_vendor_contracts',14,'Business','Client & vendor contracts',14015,true,true),
  (NULL,'business','invoices',14,'Business','Invoices raised / received',14016,true,true),
  (NULL,'system','uncategorized',99,'Uncategorized','Uncategorized',99001,true,true);

-- ── document_category_fields (encrypted_fields policy, one row per category) ─
INSERT INTO "document_category_fields" (category_id, encrypted_fields, is_active)
SELECT dc.id, v.encrypted_fields, true
  FROM (VALUES
  ('identity','aadhaar_card','aadhaar_number,date_of_birth,address,notes'),
  ('identity','pan_card','pan_number,father_name,date_of_birth,notes'),
  ('identity','passport','passport_number,date_of_birth,notes'),
  ('identity','voter_id','voter_id_number,address,notes'),
  ('identity','driving_license','license_number,blood_group,notes'),
  ('identity','birth_certificate','registration_number,date_of_birth,father_name,mother_name,notes'),
  ('identity','death_certificate','registration_number,date_of_death,notes'),
  ('identity','ration_card','ration_card_number,member_names,address,notes'),
  ('bank_investments','bank_statements_passbooks','account_number,ifsc_code,closing_balance,customer_id,net_banking_username,cards,notes'),
  ('bank_investments','fixed_deposit_receipts','fd_receipt_number,principal_amount,maturity_amount,nominee_name,notes'),
  ('bank_investments','mutual_fund_statements','folio_number,units_held,current_value,notes'),
  ('bank_investments','demat_trading_documents','demat_account_number,holdings_value,client_id,login_username,nominee_name,notes'),
  ('bank_investments','loan_agreements','loan_account_number,loan_amount,emi_amount,notes'),
  ('bank_investments','credit_card_statements','card_last_four,total_due,credit_limit,card_number,card_expiry,cvv,notes'),
  ('bank_investments','itr_form16','acknowledgement_number,pan_number,gross_income,tax_paid,notes'),
  ('bank_investments','epf_ppf_nps_statements','uan_number,account_number,closing_balance,notes'),
  ('bank_investments','cheque_books','account_number,cheque_series,notes'),
  ('bank_investments','bank_locker_agreement','locker_number,annual_rent,inventory_list,notes'),
  ('insurance','life_policies','policy_number,sum_assured,premium_amount,nominee_name,notes'),
  ('insurance','health_policies','policy_number,sum_insured,premium_amount,member_names,notes'),
  ('insurance','vehicle_policies','policy_number,registration_number,idv_amount,premium_amount,notes'),
  ('insurance','home_property_policies','policy_number,property_address,sum_insured,premium_amount,notes'),
  ('insurance','term_policies','policy_number,sum_assured,premium_amount,nominee_name,notes'),
  ('insurance','premium_receipts','receipt_number,policy_number,amount_paid,notes'),
  ('property_legal','sale_deed_title','deed_registration_number,property_address,survey_number,seller_name,buyer_name,consideration_amount,notes'),
  ('property_legal','registration_stamp_duty_receipts','receipt_number,stamp_duty_amount,registration_fee,notes'),
  ('property_legal','encumbrance_certificate','certificate_number,property_address,survey_number,notes'),
  ('property_legal','property_tax_receipts','property_id,receipt_number,amount_paid,notes'),
  ('property_legal','will_nomination','registration_number,testator_name,beneficiary_names,executor_name,witness_names,notes'),
  ('property_legal','power_of_attorney','registration_number,principal_name,attorney_name,powers_granted,notes'),
  ('property_legal','khata_mutation_certificates','khata_number,property_address,survey_number,owner_name,notes'),
  ('property_legal','divorce_custody','case_number,party_names,custody_terms,notes'),
  ('education','marksheets_certificates','roll_number,student_name,marks_obtained,percentage,notes'),
  ('education','degree_diploma','certificate_number,student_name,grade,notes'),
  ('education','migration_transfer','certificate_number,student_name,notes'),
  ('education','entrance_exam_scorecards','roll_number,candidate_name,score,rank_obtained,notes'),
  ('health_medical','records_prescriptions','patient_name,diagnosis,prescription_text,notes'),
  ('health_medical','vaccination_certificates','beneficiary_name,beneficiary_id,notes'),
  ('health_medical','checkup_reports','patient_name,test_results,notes'),
  ('health_medical','discharge_summaries','patient_name,diagnosis,treatment_summary,notes'),
  ('health_medical','insurance_claims','claim_number,policy_number,patient_name,claim_amount,approved_amount,notes'),
  ('health_medical','disability_certificate','certificate_number,person_name,disability_type,disability_percentage,notes'),
  ('employment','offer_appointment_letters','employee_name,annual_ctc,notes'),
  ('employment','salary_slips','employee_id,employee_name,gross_salary,total_deductions,net_salary,notes'),
  ('employment','experience_relieving_letters','employee_name,notes'),
  ('employment','epf_uan_documents','uan_number,pf_account_number,member_name,pf_balance,notes'),
  ('vehicle','registration_certificate','registration_number,chassis_number,engine_number,owner_name,notes'),
  ('vehicle','puc_certificate','certificate_number,registration_number,notes'),
  ('vehicle','purchase_invoice','invoice_number,chassis_number,invoice_amount,notes'),
  ('vehicle','insurance_cross_ref','policy_number,registration_number,notes'),
  ('civil_government','marriage_certificate','registration_number,spouse_names,notes'),
  ('civil_government','domicile_certificate','certificate_number,applicant_name,notes'),
  ('civil_government','caste_income_certificates','certificate_number,applicant_name,declared_value,notes'),
  ('civil_government','senior_citizen_card','card_number,date_of_birth,notes'),
  ('civil_government','oci_visa_residency','document_number,passport_number,notes'),
  ('warranty_amc','appliance_warranties','serial_number,support_contact,notes'),
  ('warranty_amc','amc_contracts','contract_number,contract_amount,support_contact,notes'),
  ('rentals_subscriptions','rental_agreements','agreement_number,property_address,landlord_name,tenant_name,monthly_rent,deposit_amount,notes'),
  ('rentals_subscriptions','subscription_receipts','subscription_id,amount_paid,notes'),
  ('utility_bills','electricity','consumer_number,service_address,bill_amount,notes'),
  ('utility_bills','gas','consumer_number,bill_amount,notes'),
  ('utility_bills','water','consumer_number,bill_amount,notes'),
  ('tax_compliance','tds_certificates','certificate_number,pan_number,deductor_tan,tds_amount,taxable_value,tax_paid,notes'),
  ('tax_compliance','advance_tax_receipts','challan_number,pan_number,amount_paid,taxable_value,tax_paid,notes'),
  ('tax_compliance','wealth_asset_declarations','declaration_number,pan_number,total_assets_value,total_liabilities_value,asset_details,notes'),
  ('tax_compliance','pension_payment_order','ppo_number,pensioner_name,bank_account_number,monthly_pension,notes'),
  ('business','registration_certificate','registration_number,notes'),
  ('business','partnership_deed_moa_aoa','cin_or_llpin,partner_names,capital_contribution,notes'),
  ('business','gst_registration_certificate','gstin,principal_place,notes'),
  ('business','gst_returns','gstin,arn_number,taxable_value,tax_payable,notes'),
  ('business','pan_tan','pan_number,tan_number,notes'),
  ('business','import_export_code','iec_code,branch_details,notes'),
  ('business','professional_tax_registration','registration_number,notes'),
  ('business','trademark_ip_registration','application_number,notes'),
  ('business','bank_statements','account_number,ifsc_code,closing_balance,notes'),
  ('business','loan_working_capital','loan_account_number,sanctioned_amount,notes'),
  ('business','insurance','policy_number,sum_insured,premium_amount,notes'),
  ('business','roc_mca_filings','cin_number,srn_number,notes'),
  ('business','audited_financials','total_revenue,net_profit,total_assets,notes'),
  ('business','employer_statutory_registrations','registration_number,employee_count,notes'),
  ('business','client_vendor_contracts','contract_number,counterparty_name,contract_value,key_terms,notes'),
  ('business','invoices','invoice_number,counterparty_name,gstin,taxable_value,tax_amount,total_amount,notes'),
  ('system','uncategorized','notes')
) AS v(module_key, document_key, encrypted_fields)
  JOIN "document_categories" dc
    ON dc.module_key = v.module_key AND dc.document_key = v.document_key
ON CONFLICT (category_id) DO NOTHING;
